#ifeq ($(MTK_FM_SUPPORT), yes)

BUILD_FM_CFG := false
BUILD_FM_PATCH := false

MTK_FM_CHIP := MT6620_FM MT6628_FM
FM_PATCH_FILE :=
FM_ROM_FILE :=
FM_COEFF_FILE :=
FM_CFG_FILE := fm_cust.cfg

LOCAL_PATH:= $(call my-dir)
FM_CUSTOM_PATH := custom/fmradio

##### MT6628 FM config: start#####
ifeq ($(findstring MT6628_FM,$(MTK_FM_CHIP)),MT6628_FM)

BUILD_FM_CFG := true
BUILD_FM_PATCH := true
FM_ROM_FILE := mt6628_fm_rom.bin
FM_PATCH_FILE_1 := mt6628_fm_v1_patch.bin
FM_COEFF_FILE_1 := mt6628_fm_v1_coeff.bin
FM_PATCH_FILE_2 := mt6628_fm_v2_patch.bin
FM_COEFF_FILE_2 := mt6628_fm_v2_coeff.bin
FM_PATCH_FILE_3 := mt6628_fm_v3_patch.bin
FM_COEFF_FILE_3 := mt6628_fm_v3_coeff.bin
FM_PATCH_FILE_4 := mt6628_fm_v4_patch.bin
FM_COEFF_FILE_4 := mt6628_fm_v4_coeff.bin
FM_PATCH_FILE_5 := mt6628_fm_v5_patch.bin
FM_COEFF_FILE_5 := mt6628_fm_v5_coeff.bin


##### INSTALL fm_cust.cfg FOR fm CONFIG #####

ifeq ($(BUILD_FM_CFG), true)
include $(CLEAR_VARS)
LOCAL_MODULE := $(FM_CFG_FILE)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/fmr
##LOCAL_SRC_FILES := custom1/mt6628/$(LOCAL_MODULE)
LOCAL_SRC_FILES := $(FM_CUSTOM_PATH)/mt6628/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)
endif

##### INSTALL fm PATCH #####

ifeq ($(BUILD_FM_PATCH), true)
include $(CLEAR_VARS)
LOCAL_MODULE := $(FM_ROM_FILE)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/mt6628
LOCAL_SRC_FILES := $(FM_CUSTOM_PATH)/mt6628/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := $(FM_PATCH_FILE_1)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/mt6628
LOCAL_SRC_FILES := $(FM_CUSTOM_PATH)/mt6628/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := $(FM_PATCH_FILE_2)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/mt6628
LOCAL_SRC_FILES := $(FM_CUSTOM_PATH)/mt6628/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := $(FM_PATCH_FILE_3)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/mt6628
LOCAL_SRC_FILES := $(FM_CUSTOM_PATH)/mt6628/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := $(FM_PATCH_FILE_4)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/mt6628
LOCAL_SRC_FILES := $(FM_CUSTOM_PATH)/mt6628/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := $(FM_PATCH_FILE_5)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/mt6628
LOCAL_SRC_FILES := $(FM_CUSTOM_PATH)/mt6628/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := $(FM_COEFF_FILE_1)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/mt6628
LOCAL_SRC_FILES := $(FM_CUSTOM_PATH)/mt6628/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := $(FM_COEFF_FILE_2)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/mt6628
LOCAL_SRC_FILES := $(FM_CUSTOM_PATH)/mt6628/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := $(FM_COEFF_FILE_3)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/mt6628
LOCAL_SRC_FILES := $(FM_CUSTOM_PATH)/mt6628/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := $(FM_COEFF_FILE_4)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/mt6628
LOCAL_SRC_FILES := $(FM_CUSTOM_PATH)/mt6628/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := $(FM_COEFF_FILE_5)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/mt6628
LOCAL_SRC_FILES := $(FM_CUSTOM_PATH)/mt6628/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

endif
endif
##### MT6628 FM config: end#####

#### MT6620 FM config: start#####
ifeq ($(findstring MT6620_FM,$(MTK_FM_CHIP)),MT6620_FM)

include $(CLEAR_VARS)
LOCAL_MODULE := mt6620_$(FM_CFG_FILE)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/fmr
LOCAL_SRC_FILES := $(FM_CUSTOM_PATH)/mt6620/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

endif
##### MT6620 FM config: end#####

include $(call all-makefiles-under,$(LOCAL_PATH))

#endif
