/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mediatek_android_application_HelloWorldJNI */

#ifndef _Included_mediatek_android_application_HelloWorldJNI
#define _Included_mediatek_android_application_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mediatek_android_application_HelloWorldJNI
 * Method:    start
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mediatek_android_application_HelloWorldJNI_start
  (JNIEnv *, jobject);

/*
 * Class:     mediatek_android_application_HelloWorldJNI
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mediatek_android_application_HelloWorldJNI_get
  (JNIEnv *, jobject);

/*
 * Class:     mediatek_android_application_HelloWorldJNI
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mediatek_android_application_HelloWorldJNI_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
